# -*- coding: utf-8 -*-
"""Meu Primeiro Algoritmo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10RGFNUuqIPRaeC0J4FVAZUCTjPolvUUu

#Operadores Aritméticos
"""

#Adição
10 + 2

#Subtração
10 - 2

#Multiplicação
10 * 2

#Divisão
10 / 2

#Divisão inteira
10 // 2

#Resto da divisão
10 % 2

#Ptenciação
10 ** 2

"""##Operadores Relacionasis"""

#Menor
10 < 2

#Menor ou iqual
10 <= 2

#Maior
10 > 2

#Maior ou iqual
10 >= 2

#Igual
7 == 7

#Diferente
7 != 7

"""#Operadores Lógicos


*   And
*   Or
*   Not

#Tabele Verdade
And




"""

print(10 > 2 and 4 < 6) #V and V -V
print(10 > 2 and 4 > 6) #V and F -F
print(10 < 2 and 4 < 6) #V and F -F
print(10 < 2 and 4 > 6) #F and F -F

"""Or"""

print(10 > 2 or 4 < 6) #V and V -V
print(10 > 2 or 4 > 6) #V and F -v
print(10 < 2 or 4 < 6) #V and F -v
print(10 < 2 or 4 > 6) #F and F -F

"""Not"""

not 10 > 2   # V - F

not 10 < 2   # F - V

"""#Variáveis

variáveis Estão alocadas em espaços na memória
"""

# Nome da Variável é "X" que armazena o valor em um  espaço na memória
x = 8
print(x) # Utilizar a referencia no nome atribuido

print("Conhecendo o  Camando Print")

y = 10
soma = x + y
print(soma)

nome = "Felipe Eduardo"
print(nome)

"""Concatenção"""

X = 5
print("O valor de x é " ,X)

print("Eu,",nome, "tirei",x,"na prova de Python")

y = 10; z = 20 + x - y
print("Declarar várias variáveis na mesma linha:",y,z)

"""Type"""

X = 10
type(x)
print("x",type(x))

nome = "Felipe"
print("nome", type(nome))

num = "100"
num_convert = int(num) # converter variável
print("num", type(num))
print ("num_conver",type(num_convert))

num_float = float(num)
print("num_float", num_float)

"""Input

* Armazenamento a informação digitada pelo usuário  em uma variável

* o dado armazenamento sempre será um texto
"""

nome =  input("Digite o nome do usuário ") # Aguarde o usuário digitar  algo
print(nome)

valor = input("Digite a nota")
print(nome,"sua nota foi", valor )

valor = input("Digite o valor do produto: ")
print(valor)

desconto = valor - 5

valor_convet = int(valor)

desconto = valor_convet - 5
print(desconto)

Desconto = valor_convet - 5
print(desconto)

"""#Estrutura  condicionado

##condicional
"""

# If
if 5 < 10:
  print("Verdade")

# If/else
num1 = 10
num2 = 5
if num1 > num2:
  print("O num1 é  o maior número")

else:
    print("O num2 é o maior número")

# If / Elif / Eslse
num1 = 10
num2 = 10
if num1 > num2:
  print("O num1 é o maior número")
elif num1 < num2:
  print("O num2 é o maior número")

else:
  print("Os doi são iguais")

"""#Condicional com operadores lógicos"""

num1 = 10
num2 = 5
num3 = 2
if (num1 > num2) and (num1 > num3):
  print("o num1 é o maior número")
else :
  print("o num1 não é o maior ´numero")

"""# Lista de vslores , tuplas e dicionários

"""

#lisata
[1,2,3,4,5]

# Tupla
(1,2,3,4,5)

# Dicionário
{"num1":1, "num2": 2}

"""#Lista"""

lista = [5, "Felipe", 8.9]

type(lista)

lista.append("Augusto") # Adcionar um elemento na lista

print(lista)
print(lista[1])

"""#Tupla"""

tupla = (5, "Felipe, 8.9")

type(tupla)

tupla.append("Augusto")

print(tupla)

"""#Dicionário"""

dicionario ={"nome": "Felipe","cidade": "São josé dps Campos"}

type(dicionario)

print(dicionario)

print(dicionario["nome"])

dicionario["ultimo_nome"] = "rebouças"

print(dicionario)

"""# Estrutura de repetição

##For
"""

# for Rage
for contador in range(10):
  print(contador)

# for Renge + Break
for contador in range(1000):
  print(contador)
  if contador == 8:
    break

lista = [ "Teste1","Teste2"]

# For Simples
for val in lista:
  print(val)

# for com Enumerate
for i, val in enumerate(lista):
  print(i, val )

"""## For com operadores compostos"""

lista2 = [2,3,4]

for val in lista2:
  val +=1
  print(val)

for val in lista2:
  val*= 2
  print(val)

"""##While"""

val = 1
while (val < 6):
  val *=2
  print(val)

#Whale com else
val = 10
while val < 6:
  val*=2
else:
    print("Valor de val é:", val)

"""# Olho no codigo"""

# Obtém o nome do usuário
nome = input("Digite seu nome:")
print("Olá,"+ nome + "!")

"""## Verificção de senha simples"""

# Definir a senha permitida
senha_permitida = "12345"

# Solicitar a senha do usuário
senha_Usuario = input ("Digite a senha ")

# Vericar se a senha estaá correta
if senha_Usuario == senha_permitida:
  print("Acessopermitido!")
else:
  print("Senha incoreeta. Acesso Negado")

"""# Orgonizando dados de feedback de clientes"""

# Lista de feedbacks
feedbacks = ["Ótimo serviço!","Produto excelente","Atendimento rápido" ]

# Dicionário com informações de um cliente
Cliente = {
    "nome": "Maria",
    "idade": 28,
    "feedback": "Muito satisfeito"
  }

# Imprimi  os feedbacks da lista
print("Feedbacks dos clientes:")
for feedback in feedbacks:
  print("- " + feedback )

  # Imprimir informações  de cliente
  print("\ninformações do cliente")
  print("Nome:",  Cliente["nome"])
  print("Idade:", Cliente["idade"])
  print("Feedback:", Cliente["feedback"])

# Loop whaile

contador = 0
while contador < 5:
  print("Isso é a iteração número", contador)
  contador += 1

# Loop for

frutas = ["maçã", "banana", "laranja"]
for fruta in frutas:
  print("Eu gosto de", fruta)

# Lista de notas dos alunos
notas = [86, 92, 78, 88]

# Calcula a média das notas
soma = 0
for nota in notas:
  soma += nota
media = soma / len(notas)

# Classifica os alunas com base na média
alunos_aprovados = []
alunos_reprovados = []

for nota in notas:
  if nota >= media:
    alunos_aprovados.append(nota)
  else:
    alunos_reprovados.append(nota)

    # Imprime os reultados
    print("Notas das alunos:", notas)
    print("Média das notas:", media)
    print("Alunos aprovados:", alunos_aprovados)
    print("Alunos Reprovados:", alunos_reprovados)

# Solicita o nome do usuário e o exibe
nome_usuario = input("Por favor, insira seu nome: ")
print(f"Olá, {nome_usuario}! Bem-vindo ao nosso sistema.")

# Solicita a idade do usuário e converte para inteiro
idade_usuario = int(input("Por favor, insira sua idade: "))

# Verifica se o usuário é maior de idade
if idade_usuario >= 18:
    print("Você é maior de idade.")
else:
    print("Você é menor de idade.")

idade = int(input("Digite sua idade: "))
if idade > 18:
    print("Maior de idade")

x = 10
if x == 10:
    print("Operador correto")

total = 1
total = total + 8
print(total)

idade = 20
renda = 3000
if (idade > 18 and renda > 2000) or idade < 25:
    print("Aprovado")

n1 = input("Digite o numero ") # Aguarde o numero 1 digitar
print(n1)


operadores = input("Digite o símbolo de operação ") # Aguarde o símbolo de operação digitar
print(operadores)


n2 = input("Digite o numero ") # Aguarde o numero 2 digitar
print(n2)

# Converter strings em inteiros
num1 = int(n1)
num2 = int(n2)

# Execute a operação com base no operador
if operadores == '+':
  resultado = num1 + num2
elif operadores == '-':
  resultado = num1 - num2
elif operadores == '*':
  resultado = num1 * num2
elif operadores == '/':

  # Adicione uma verificação para divisão por zero
  if num2 != 0:
    resultado = num1 / num2
  else:
    resultado = "Erro: Divisão por zero!"
else:
  resultado = "Erro: Operador inválido!"

print("Resultado ", resultado)

n1 = input("Digite o numero ") # Aguarde o numero 1 digitar
print(n1)


operadores = input("Digite o símbolo de operação ") # Aguarde o símbolo de operação digitar
print(operadores)


n2 = input("Digite o numero ") # Aguarde o numero 2 digitar
print(n2)

# Converter strings em inteiros
num1 = int(n1)
num2 = int(n2)

# Execute a operação com base no operador
if operadores == '+':
  resultado = num1 + num2
elif operadores == '-':
  resultado = num1 - num2
elif operadores == '*':
  resultado = num1 * num2
elif operadores == '/':

  # Adicione uma verificação para divisão por zero
  if num2 != 0:
    resultado = num1 / num2
  else:
    resultado = "Erro: Divisão por zero!"
else:
  resultado = "Erro: Operador inválido!"

print("Resultado ", resultado)

"""# Divisor"""

# Saber ser numeros r divisor!


valor1 = input("Digite o número ")
print(valor1)
valor2 = input("Digite o número ")
print(valor2)

valor1 = int(valor1)
valor2 = int(valor2)

if valor1 > valor2:
  resto = valor1 % valor2
  if resto == 0:

   print("O", valor2, "é um divisor de", valor1)

  else:
    print("O", valor2, "não é um divisor de", valor1)

  print("O", valor1, "é  o maior número")

elif valor1 < valor2:
  resto = valor2 % valor1
  if resto == 0:
    print("O", valor1, "é um divisor de", valor2)

"""#Cotação do dolar hoje"""

# converter dolar em reasis

# hoje 22/07/2025 dolar = 5.56

saber = input("você que saber o valor do dolar hoje ou do real?")
print(saber)



dolar = input("Digite a cotação do dolar hoje: ")
real = input("Digite o quanto em dolor você tem: ")

dolar = float(dolar)
real = float(real)
saber = str(saber)

resultado = 0

if saber == "dolar":
  resultado = real * dolar

elif saber == "real":
  resultado = real * dolar

else: print("Resultado",resultado )

# converter dolar em reasis

# hoje 22/07/2025 dolar = 5.56

dolar = 0
real = 0
cotacaoDolar = 0

print("se vocês quer converter  de  Real para Dólar, digite 1 ou 2")
resposta = int(input("Digite a opção: "))
print(resposta)


if resposta == 1:
  print("Vamos converter de Real para Dólar")
  dolar = float(input("Digite a cotação do Dólar hoje: "))
  real = float(input("Digite o quanto em Real você tem: "))
  dolar = dolar * real
  print("Você tem", dolar, "dólares")

elif resposta == 2:
  print("Vamos converter de Dólar para Real")
  real = float(input("Digite a cotação do Dólar hoje: "))
  dolar = float(input("Digite o quanto em Dólar você tem: "))
  real = dolar / real
  print("Você tem", real, "reais")


else:
  print("Opção inválida")

"""

```
# Isto está formatado como código
```

# É par ou inpar"""



# informações iniciais

print("Caculadora")
print("Vou te ajudar, vamos começar")

nome = input("Qual o seu nome? ")
print("Olá ", nome)

  # Solicita os números e o operador

n1 = input("Digite o primeiro número: ")
operador = input("Digite o símbolo de operação (+, -, *, /, %): ")
n2 = input("Digite o segundo número: ")

  # Converter strings em inteiros

num1 = float(n1)
num2 = float(n2)

  # Executa a operação com base no operador

if operador == '+':
  resultado = num1 + num2
elif operador == '-':
  resultado = num1 - num2
elif operador == '*':
  resultado = num1 * num2
elif operador == '/':
  if num2 != 0:
    resultado = num1 / num2
  else:
    resultado = "Erro: Divisão por zero!"
elif operador == '%':
  if num2 != 0:
    resultado1 = num1 * num2
    resultado = resultado1  / 100
  else:
    resultado = "Erro: Módulo por zero!"
else:
    resultado = "Erro: Operador inválido!"

  # Executa de resultado final

print(nome,"Resultado:", resultado)